### ISSUE TITLE
Moving ec2 (10) resources to v1beta1 version

### ISSUE THREAD

**Issue by dverveiko** [crossplane-contrib/provider-upjet-aws#132]
Moving 10 resources in the `ec2` group:

- [ ] [`aws_ec2_client_vpn_endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint) - Depend on untested `aws_cloudwatch_log_stream` resource
- [ ] [`aws_ec2_client_vpn_authorization_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_authorization_rule) - Depend on `aws_ec2_client_vpn_endpoint` resource
- [ ] [`aws_ec2_client_vpn_network_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_network_association) - Depend on `aws_ec2_client_vpn_endpoint` resource
- [ ] [`aws_ec2_client_vpn_route`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_route) - Depend on `aws_ec2_client_vpn_endpoint` resource

- [ ] [`aws_ec2_fleet`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_fleet) - Depend on bug(https://github.com/upbound/provider-aws/issues/118)

- [ ] [`aws_ec2_local_gateway_route`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_local_gateway_route) - Depend on bug(https://github.com/upbound/provider-aws/issues/112)

- [ ] [`aws_ec2_local_gateway_route_table_vpc_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_local_gateway_route_table_vpc_association) - Uses expensive resources - ON HOLD

- [ ] [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) - Depend on untested `aws_vpn_connection` resource

- [ ] [`aws_ec2_traffic_mirror_target`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_traffic_mirror_target) - Depend on bug(https://github.com/upbound/provider-aws/issues/113)
- [ ] [`aws_ec2_traffic_mirror_session`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_traffic_mirror_session) - Depend on `aws_ec2_traffic_mirror_target` resource
