### ISSUE TITLE
Prioritize Popular AWS Services

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/provider-upjet-aws#39]
After https://github.com/upbound/official-providers/issues/304 and https://github.com/upbound/official-providers/issues/305 we should prioritize configuring the remaining resources from the most popular AWS services.+

Milestone https://github.com/upbound/official-providers/milestone/6

# Most Popular AWS Services

- [ ] CloudTrail https://github.com/upbound/provider-aws/issues/35
- [x] CloudWatch https://github.com/upbound/official-providers/issues/438
- [x] DynamoDB https://github.com/upbound/official-providers/issues/252
- [ ] Elastic Compute Cloud (EC2)
  - [x] https://github.com/upbound/provider-aws/issues/30
  - [x] https://github.com/upbound/provider-aws/issues/65
  - [x] https://github.com/upbound/official-providers/issues/254
- [x] Elastic Container Service (ECS) https://github.com/upbound/official-providers/issues/439
- [ ] Elastic Load Balancing (ELB) https://github.com/upbound/provider-aws/issues/45
- [ ] ElastiCache https://github.com/upbound/provider-aws/issues/34
- [x] Key Management Service (KMS)
- [x] Lambda
- [ ] Relational Database Service (RDS) https://github.com/upbound/provider-aws/issues/48
- [x] Route53
- [x] SecretsManager https://github.com/upbound/official-providers/issues/381
- [ ] Simple Notification Service (SNS) https://github.com/upbound/provider-aws/issues/47
- [x] Simple Queuing Service (SQS) https://github.com/upbound/official-providers/issues/385
- [x] Simple Storage Service (S3) 
- [ ] Virtual Private Cloud (VPC) https://github.com/upbound/provider-aws/issues/53

Sources:
https://www.quora.com/What-are-the-popular-AWS-services 
https://www.jeffersonfrank.com/insights/aws-products
https://www.2ndwatch.com/blog/the-most-popular-aws-products-of-2020/
https://www.eginnovations.com/ebook/apm-survey-2021-report.pdf
